version: "3"
services:
  api:
    build: snymanc:fastapi
    ports:
      - 80:8000
    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - OAUTH2_SECRET_KEY=${OAUTH2_SECRET_KEY}
      - OAUTH2_ALGORITHM=${OAUTH2_ALGORITHM}
      - OAUTH2_ACCESS_TOKEN_EXPIRE_MINUTES=${OAUTH2_ACCESS_TOKEN_EXPIRE_MINUTES}
    
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
