version: "3"

services:

  api:
    build: .
    ports:
      - 8000:8000
    env_file:
      - ./.env
    # environment:
    #   - DATABASE_HOSTNAME=localhost
    #   - DATABASE_PORT=5432
    #   - DATABASE_NAME=fastapi2
    #   - DATABASE_USERNAME=postgres
    #   - DATABASE_PASSWORD=GarthNeele
    #   - OAUTH2_SECRET_KEY="5235d21776b207cd601b8a2f99fb1077aaa92cc1a5f94d7dda7ac1bbaf8ed62f"
    #   - OAUTH2_ALGORITHM="HS256"
    #   - OAUTH2_ACCESS_TOKEN_EXPIRE_MINUTES=30
