version: "3"

services:

  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro
    # env_file:
    #   - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=fastapi2
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=GarthNeele
      - OAUTH2_SECRET_KEY="5235d21776b207cd601b8a2f99fb1077aaa92cc1a5f94d7dda7ac1bbaf8ed62f"
      - OAUTH2_ALGORITHM="HS256"
      - OAUTH2_ACCESS_TOKEN_EXPIRE_MINUTES=30
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=GarthNeele
      - POSTGRES_DB=fastapi2

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
